# Generated by Django 3.2.6 on 2021-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_logic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="contrib_frequency",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("BI_WEEKLY", "Bi-Weekly"),
                    ("WEEKLY", "Weekly"),
                    ("NA", "N/A"),
                ],
                default="MONTHLY",
                max_length=32,
            ),
        ),
    ]
