version: "3.1"

services:
  db:
    restart: always
    image: postgres
    container_name: buckets-postgres
    environment:
      - POSTGRES_USER=$BUCKETS_DB_USER
      - POSTGRES_PASSWORD=$BUCKETS_DB_PASS
      - POSTGRES_DB=$BUCKETS_DB_NAME
      - POSTGRES_PORT=$BUCKETS_DB_PORT
    ports:
      - "$BUCKETS_DB_PORT:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
