version: "3.7"

services:
  db:
    restart: always
    image: postgres
    container_name: buckets-postgres
    environment:
      - POSTGRES_USER=$BUCKETS_DB_USER
      - POSTGRES_PASSWORD=$BUCKETS_DB_PASS
      - POSTGRES_DB=$BUCKETS_DB_NAME
      - POSTGRES_PORT=$BUCKETS_DB_PORT
    ports:
      - "$BUCKETS_DB_PORT:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    restart: "on-failure"
    image: buckets:0.1-beta-1
  nginx:
    build: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
