version: "3.7"

services:
  db:
    restart: unless-stopped
    image: postgres
    container_name: buckets-postgres
    environment:
      - POSTGRES_USER=$BUCKETS_DB_USER
      - POSTGRES_PASSWORD=$BUCKETS_DB_PASS
      - POSTGRES_DB=$BUCKETS_DB_NAME
      - POSTGRES_PORT=$BUCKETS_DB_PORT
    volumes:
      - database-data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - $BUCKETS_REDIS_PORT:$BUCKETS_REDIS_PORT
    command: redis-server --save 20 1 --loglevel warning --requirepass $BUCKETS_REDIS_PASSWORD
    volumes:
      - redis:/data

volumes:
  database-data:
  redis:
    driver: local
