# Generated by Django 3.2.6 on 2021-09-20 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='contrib_frequeny',
            new_name='contrib_frequency',
        ),
        migrations.AlterField(
            model_name='goal',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='goal',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='backend.bucket'),
        ),
    ]
