# Generated by Django 3.2.6 on 2021-08-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_goals_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal',
            new_name='goal_amount',
        ),
    ]
