name: Deployment Workflow

on:
  release:
    types: [published]

jobs:
  deployment:
    name: Build, Deploy and Startup buckets
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nnamdiibe/buckets

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Copy over docker-compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BUCKETS_SERVER_HOST }}
          username: ${{ secrets.BUCKETS_SERVER_USERNAME }}
          key: ${{ secrets.BUCKETS_SERVER_SSH_KEY }}
          passphrase: ${{ secrets.BUCKETS_SERVER_SSH_PASSPHRASE }}
          port: ${{ secrets.BUCKETS_SERVER_PORT }}
          source: "backend/docker-compose.prod.yml"
          target: ${{ secrets.BUCKETS_SCP_DIRECTORY }}
          strip_components: 1

      - name: Copy over nginx.conf to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BUCKETS_SERVER_HOST }}
          username: ${{ secrets.BUCKETS_SERVER_USERNAME }}
          key: ${{ secrets.BUCKETS_SERVER_SSH_KEY }}
          passphrase: ${{ secrets.BUCKETS_SERVER_SSH_PASSPHRASE }}
          port: ${{ secrets.BUCKETS_SERVER_PORT }}
          source: "backend/nginx/conf.d/nginx.conf"
          target: ${{ secrets.BUCKETS_NGINX_SCP_DIRECTORY }}
          strip_components: 3

      - name: ssh into server, build images & startup containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BUCKETS_SERVER_HOST }}
          username: ${{ secrets.BUCKETS_SERVER_USERNAME }}
          key: ${{ secrets.BUCKETS_SERVER_SSH_KEY }}
          passphrase: ${{ secrets.BUCKETS_SERVER_SSH_PASSPHRASE }}
          port: ${{ secrets.BUCKETS_SERVER_PORT }}
          script: |
            cd ${{ secrets.BUCKETS_SCP_DIRECTORY }}
            export BUCKETS_IMAGE_TAG=${{ steps.meta.outputs.version }}
            docker ps
            echo "Building images, starting containers"
            docker-compose -f docker-compose.prod.yml up -d
            echo "Containers status"
            docker ps
