name: Djano Tests

on: [push, pull_request]

jobs:
  build:
    env:
      BUCKETS_DB_USER: postgres
      BUCKETS_DB_PASS: postgres
      BUCKETS_DB_NAME: postgres
      BUCKETS_DB_PORT: 5432
      BUCKETS_DB_HOST: localhost
    runs-on: ubuntu-latest
        
    services:
      postgres:
        image: postgres:12.5
        env:
          POSTGRES_USER: ${{ env.BUCKETS_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.BUCKETS_DB_PASS }}
          POSTGRES_DB: ${{ env.BUCKETS_DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install pipenv
        pipenv install --deploy --dev
    - name: Run Tests
      run: |
        pipenv run python manage.py test
