name: Flutter Tests

on: [push, pull_request]

jobs:
  tests:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.2'
    - name: Install Packages
      run: flutter pub get
    - name: Analyze
      run: make lint
    - name: Run tests
      run: flutter test
